name: Update emails

on:
  schedule:
    - cron: 0 1-5,7-10,14 * * 1-5   # 8h, 9h, 10h, 11h, 12h, 14h, 15h, 16h, 17h, 21h on weekdays in Vietnam
    - cron: 0 2,8 * * 6,0           # 9h, 15h on weekends in Vietnam

jobs:
  update-data:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.12
          cache: true
          cache-dependency-path: |
            ./pdm.lock

      - name: Install dependencies
        run: pdm sync

      - name: Update emails
        env:
          IMAP_HOST: ${{ secrets.IMAP_HOST }}
          IMAP_PORT: ${{ secrets.IMAP_PORT }}
          IMAP_EMAIL: ${{ secrets.IMAP_EMAIL }}
          IMAP_PASSWORD: ${{ secrets.IMAP_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: pdm run src/main.py
